name: C/C++ CI (Windows XP)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-winxp:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Build for Windows XP
      shell: cmd
      run: ./.github/workflow_build_winxp.bat

    - uses: actions/upload-artifact@master
      with:
        name: Main UI binary
        path: build/ui/release/ui.exe
      name: upload-ui-build
